model:
    value: single_edit
mpnn:
    value: graph_feat
mpn_size:
    value: 256
depth:
    value: 10
dropout_mpn:
    value: 0.15
mlp_size:
    value: 512
dropout_mlp:
    value: 0.3
rnn_type:
    value: gru
clip_norm:
    value: 10.0
loss_type:
    value: softmax
edits_type:
    value: bond_edits
lr:
    value: 0.001
pos_weight:
    value: 5.0
propagate_logits:
    value: true
print_every:
    value: 200
eval_every:
    value: 600
scheduler_type:
    value: plateau
anneal_rate:
    value: 0.9
metric_thresh:
    value: 0.01
patience:
    value: 10
epochs:
    value: 200
use_prod_edits:
    value: true
